### ISSUE TITLE
License

### ISSUE THREAD

**Issue by warpling** [netguy204/liquids#1]
Hi Brian,

Would you consider [adding a license](https://help.github.com/articles/open-source-licensing/) to this project? I'm having a lot of fun playing with it and would like to see if I can use it in part of an app I'm working on.

**Comment by netguy204** [comment]
Hope this is what you were looking for. I'd love to see what you put this into!

**Comment by warpling** [comment]
Perfect! Thank you so much.
I'll let you know when it's ready :)
